(******************************************************************************)
(*                                                                            *)
(*            Inter-Universal Teichmüller Theory: The abc Arbiter             *)
(*                                                                            *)
(*     Formalizes Mochizuki's IUT (2012): Hodge theaters, Frobenioids,        *)
(*     log-theta lattices, and the disputed Corollary 3.12. Either the        *)
(*     proof compiles or it doesn't. Machine-checked resolution of a          *)
(*     decade-long controversy that human consensus could not settle.         *)
(*                                                                            *)
(*     "The abc conjecture is the most important unsolved problem in          *)
(*     Diophantine analysis."                                                 *)
(*     - Dorian Goldfeld, 1996                                                *)
(*                                                                            *)
(*     Author: Charles C. Norton                                              *)
(*     Date: January 8, 2026                                                  *)
(*     License: MIT                                                           *)
(*                                                                            *)
(******************************************************************************)
